export const theme = {
  name: "10004ok",
  type: "dark",
  colors: {
    "activityBar.activeBackground": "#323e53",
    "activityBar.activeBorder": "#e34f8c",
    "activityBar.background": "#0f172a",
    "activityBar.border": "#1e293b",
    "activityBar.foreground": "#ffdc8c",
    "activityBar.inactiveForeground": "#ffffff66",
    "activityBarBadge.background": "#15334f",
    "activityBarBadge.foreground": "#38bdf8",
    "badge.background": "#15334f",
    "badge.foreground": "#38bdf8",
    "breadcrumb.activeSelectionForeground": "#e0e0e0",
    "breadcrumb.background": "#1e293b",
    "breadcrumb.focusForeground": "#e0e0e0",
    "breadcrumb.foreground": "#cccccccc",
    "button.background": "#0ea5e9",
    "button.foreground": "#ffffff",
    "button.hoverBackground": "#38bdf8",
    "button.secondaryBackground": "#1e293b",
    "button.secondaryForeground": "#94a3b8",
    "button.secondaryHoverBackground": "#334155",
    "checkbox.background": "#2b3447",
    "checkbox.border": "#00000000",
    "checkbox.foreground": "#cccccc",
    "debugExceptionWidget.background": "#0f172a",
    "debugExceptionWidget.border": "#1e293b",
    "debugToolBar.background": "#0f172a",
    "debugToolBar.border": "#1e293b",
    "diffEditor.border": "#444444",
    "diffEditor.insertedTextBackground": "#9bb95530",
    "diffEditor.removedTextBackground": "#ff000033",
    "dropdown.background": "#0f172a",
    "dropdown.border": "#00000000",
    "dropdown.foreground": "#cccccc",
    "editor.background": "#1e293b",
    "editor.findMatchBackground": "#515c6a",
    "editor.findMatchBorder": "#74879f",
    "editor.findMatchHighlightBackground": "#ea5c0055",
    "editor.findMatchHighlightBorder": "#ffffff00",
    "editor.findRangeHighlightBackground": "#3a3d4166",
    "editor.findRangeHighlightBorder": "#ffffff00",
    "editor.foldBackground": "#264f784d",
    "editor.foreground": "#d6d6d6",
    "editor.hoverHighlightBackground": "#264f7840",
    "editor.inactiveSelectionBackground": "#264f7890",
    "editor.lineHighlightBackground": "#ffffff0a",
    "editor.lineHighlightBorder": "#2a3143",
    "editor.rangeHighlightBackground": "#ffffff0b",
    "editor.rangeHighlightBorder": "#ffffff00",
    "editor.selectionBackground": "#2d4358",
    "editor.selectionHighlightBackground": "#add6ff26",
    "editor.selectionHighlightBorder": "#495f77",
    "editor.wordHighlightBackground": "#575757b8",
    "editor.wordHighlightStrongBackground": "#004972b8",
    "editorBracketHighlight.foreground1": "#7ec1d4",
    "editorBracketHighlight.foreground2": "#f6a992",
    "editorBracketHighlight.foreground3": "#71d8a6",
    "editorBracketHighlight.unexpectedBracket.foreground": "#db6165",
    "editorBracketMatch.background": "#0064001a",
    "editorBracketMatch.border": "#888888",
    "editorCodeLens.foreground": "#999999",
    "editorCursor.background": "#000000",
    "editorCursor.foreground": "#FFD500",
    "editorError.background": "#b73a3400",
    "editorError.border": "#ffffff00",
    "editorError.foreground": "#f48771",
    "editorGroup.border": "#151515",
    "editorGroup.emptyBackground": "#0d1628",
    "editorGroupHeader.border": "#1e293b",
    "editorGroupHeader.tabsBackground": "#283447",
    "editorGutter.addedBackground": "#587c0c",
    "editorGutter.background": "#1e293b",
    "editorGutter.commentRangeForeground": "#c5c5c5",
    "editorGutter.deletedBackground": "#94151b",
    "editorGutter.foldingControlForeground": "#c5c5c5",
    "editorGutter.modifiedBackground": "#0c7d9d",
    "editorHoverWidget.background": "#1e293b",
    "editorHoverWidget.border": "#0e131b",
    "editorHoverWidget.foreground": "#e2e8f0",
    "editorIndentGuide.activeBackground": "#707070",
    "editorIndentGuide.background": "#ffffff0f",
    "editorInfo.background": "#4490bf00",
    "editorInfo.border": "#4490bf00",
    "editorInfo.foreground": "#75beff",
    "editorLineNumber.activeForeground": "#c6c6c6",
    "editorLineNumber.foreground": "#475569",
    "editorLink.activeForeground": "#4e94ce",
    "editorMarkerNavigation.background": "#0f172a",
    "editorMarkerNavigationError.background": "#f4877199",
    "editorMarkerNavigationInfo.background": "#75beff99",
    "editorMarkerNavigationWarning.background": "#cca70099",
    "editorOverviewRuler.background": "#25252500",
    "editorOverviewRuler.border": "#7f7f7f4d",
    "editorRuler.foreground": "#5a5a5a",
    "editorSuggestWidget.background": "#334155",
    "editorSuggestWidget.border": "#334155",
    "editorSuggestWidget.foreground": "#efeff1",
    "editorSuggestWidget.highlightForeground": "#7dd3fc",
    "editorSuggestWidget.selectedBackground": "#475569",
    "editorSuggestWidget.selectedForeground": "#ffdc8c",
    "editorWarning.background": "#a9904000",
    "editorWarning.border": "#ffffff00",
    "editorWarning.foreground": "#cca700",
    "editorWhitespace.foreground": "#e3e4e229",
    "editorWidget.background": "#0f172a",
    "editorWidget.foreground": "#cccccc",
    "editorWidget.resizeBorder": "#38bdf8",
    focusBorder: "#007fd4",
    foreground: "#cccccc",
    "gitDecoration.addedResourceForeground": "#81b88b",
    "gitDecoration.conflictingResourceForeground": "#6c6cc4",
    "gitDecoration.deletedResourceForeground": "#c74e39",
    "gitDecoration.ignoredResourceForeground": "#8c8c8c",
    "gitDecoration.modifiedResourceForeground": "#e2c08d",
    "gitDecoration.stageDeletedResourceForeground": "#c74e39",
    "gitDecoration.stageModifiedResourceForeground": "#e2c08d",
    "gitDecoration.submoduleResourceForeground": "#8db9e2",
    "gitDecoration.untrackedResourceForeground": "#73c991",
    "icon.foreground": "#cccccc",
    "input.background": "#0f172a",
    "input.border": "#00000000",
    "input.foreground": "#cccccc",
    "input.placeholderForeground": "#a6a6a6",
    "inputOption.activeBackground": "#007fd466",
    "inputOption.activeBorder": "#007acc00",
    "inputOption.activeForeground": "#ffffff",
    "list.activeSelectionBackground": "#1e293b",
    "list.activeSelectionForeground": "#ffffff",
    "list.dropBackground": "#1e293b",
    "list.focusBackground": "#062f4a",
    "list.focusForeground": "#cccccc",
    "list.highlightForeground": "#0097fb",
    "list.hoverBackground": "#1e293b",
    "list.hoverForeground": "#cccccc",
    "list.inactiveSelectionBackground": "#1e293b",
    "list.inactiveSelectionForeground": "#cccccc",
    "listFilterWidget.background": "#15334e",
    "listFilterWidget.noMatchesOutline": "#be1100",
    "listFilterWidget.outline": "#00000000",
    "menu.background": "#0f172a",
    "menu.border": "#1e293b",
    "menu.foreground": "#cccccc",
    "menu.selectionBackground": "#094771",
    "menu.selectionBorder": "#1e293b",
    "menu.selectionForeground": "#ffffff",
    "menu.separatorBackground": "#bbbbbb",
    "menubar.selectionBackground": "#ffffff1a",
    "menubar.selectionForeground": "#cccccc",
    "merge.commonContentBackground": "#282828",
    "merge.commonHeaderBackground": "#383838",
    "merge.currentContentBackground": "#27403b",
    "merge.currentHeaderBackground": "#367366",
    "merge.incomingContentBackground": "#28384b",
    "merge.incomingHeaderBackground": "#395f8f",
    "minimap.background": "#0d1628",
    "minimap.errorHighlight": "#f48771",
    "minimap.findMatchHighlight": "#515c6a",
    "minimap.selectionHighlight": "#2d4358",
    "minimap.warningHighlight": "#cca700",
    "minimapGutter.addedBackground": "#587c0c",
    "minimapGutter.deletedBackground": "#94151b",
    "minimapGutter.modifiedBackground": "#0c7d9d",
    "notificationCenter.border": "#1e293b",
    "notificationCenterHeader.background": "#1e293b",
    "notificationCenterHeader.foreground": "#cccccc",
    "notificationToast.border": "#1e293b",
    "notifications.background": "#0f172a",
    "notifications.border": "#1e293b",
    "notifications.foreground": "#cccccc",
    "notificationsErrorIcon.foreground": "#f48771",
    "notificationsInfoIcon.foreground": "#75beff",
    "notificationsWarningIcon.foreground": "#cca700",
    "panel.background": "#131c30",
    "panel.border": "#1e293b",
    "panelSection.border": "#1e293b",
    "panelTitle.activeBorder": "#38bdf8",
    "panelTitle.activeForeground": "#e7e7e7",
    "panelTitle.inactiveForeground": "#748296",
    "peekView.border": "#353f4f",
    "peekViewEditor.background": "#1e293b",
    "peekViewEditor.matchHighlightBackground": "#283447",
    "peekViewEditor.matchHighlightBorder": "#566377",
    "peekViewEditorGutter.background": "#001f33",
    "peekViewResult.background": "#283447",
    "peekViewResult.fileForeground": "#cdcdcd",
    "peekViewResult.lineForeground": "#bbbbbb",
    "peekViewResult.matchHighlightBackground": "#ea5c004d",
    "peekViewResult.selectionBackground": "#3399ff33",
    "peekViewResult.selectionForeground": "#ffffff",
    "peekViewTitle.background": "#283447",
    "peekViewTitleDescription.foreground": "#ccccccb3",
    "peekViewTitleLabel.foreground": "#7dd3fc",
    "pickerGroup.border": "#1e293b",
    "pickerGroup.foreground": "#3794ff",
    "progressBar.background": "#0e70c0",
    "scrollbar.shadow": "#000000",
    "scrollbarSlider.activeBackground": "#a1a1a1",
    "scrollbarSlider.background": "#676767",
    "scrollbarSlider.hoverBackground": "#7b7b7b",
    "selection.background": "#256aa7",
    "settings.focusedRowBackground": "#ffffff07",
    "settings.headerForeground": "#cccccc",
    "sideBar.background": "#0f172a",
    "sideBar.border": "#1e293b",
    "sideBar.dropBackground": "#1e293b",
    "sideBar.foreground": "#cccccc",
    "sideBarSectionHeader.background": "#00000000",
    "sideBarSectionHeader.border": "#cccccc33",
    "sideBarSectionHeader.foreground": "#cccccc",
    "sideBarTitle.foreground": "#ffffff",
    "statusBar.background": "#1e293b",
    "statusBar.debuggingBackground": "#cc6633",
    "statusBar.debuggingForeground": "#ffffff",
    "statusBar.foreground": "#ffffff",
    "statusBar.noFolderBackground": "#68217a",
    "statusBar.noFolderForeground": "#ffffff",
    "statusBarItem.activeBackground": "#ffffff25",
    "statusBarItem.hoverBackground": "#ffffff1f",
    "statusBarItem.remoteBackground": "#16825d",
    "statusBarItem.remoteForeground": "#ffffff",
    "tab.activeBackground": "#1e293b",
    "tab.activeBorder": "#00000000",
    "tab.activeBorderTop": "#00000000",
    "tab.activeForeground": "#7dd3fc",
    "tab.border": "#1e293b",
    "tab.hoverBackground": "#1e293b90",
    "tab.hoverBorder": "#1e293b",
    "tab.inactiveBackground": "#283447",
    "tab.inactiveForeground": "#ffffff80",
    "terminal.ansiBlack": "#000000",
    "terminal.ansiBlue": "#c7adfb",
    "terminal.ansiBrightBlack": "#666666",
    "terminal.ansiBrightBlue": "#3b8eea",
    "terminal.ansiBrightCyan": "#29b8db",
    "terminal.ansiBrightGreen": "#23d18b",
    "terminal.ansiBrightMagenta": "#d670d6",
    "terminal.ansiBrightRed": "#f14c4c",
    "terminal.ansiBrightWhite": "#e5e5e5",
    "terminal.ansiBrightYellow": "#f5f543",
    "terminal.ansiCyan": "#11a8cd",
    "terminal.ansiGreen": "#51e1a5",
    "terminal.ansiMagenta": "#bc3fbc",
    "terminal.ansiRed": "#cd3131",
    "terminal.ansiWhite": "#e5e5e5",
    "terminal.ansiYellow": "#51e1a5",
    "terminal.border": "#1e293b",
    "terminal.foreground": "#cccccc",
    "terminal.selectionBackground": "#ffffff10",
    "terminalCursor.background": "#0087ff",
    "terminalCursor.foreground": "#ffffff",
    "textLink.foreground": "#3794ff",
    "titleBar.activeBackground": "#0f172a",
    "titleBar.activeForeground": "#cccccc",
    "titleBar.border": "#00000000",
    "titleBar.inactiveBackground": "#12192a",
    "titleBar.inactiveForeground": "#cccccc99",
    "tree.indentGuidesStroke": "#585858",
    "walkThrough.embeddedEditorBackground": "#00000050",
    "widget.shadow": "#0000005c",
    "activityBar.dropBorder": "#ffdc8c",
    "banner.background": "#1e293b",
    "banner.foreground": "#ffffff",
    "banner.iconForeground": "#75beff",
    "breadcrumbPicker.background": "#0f172a",
    "button.separator": "#ffffff66",
    "charts.blue": "#75beff",
    "charts.foreground": "#cccccc",
    "charts.green": "#89d185",
    "charts.lines": "#cccccc80",
    "charts.orange": "#515c6a",
    "charts.purple": "#b180d7",
    "charts.red": "#f48771",
    "charts.yellow": "#cca700",
    "commandCenter.activeBackground": "#ffffff1a",
    "commandCenter.activeForeground": "#cccccc",
    "commandCenter.border": "#1e293b",
    "commandCenter.foreground": "#cccccc",
    "debugConsole.errorForeground": "#f48771",
    "debugConsole.infoForeground": "#75beff",
    "debugConsole.sourceForeground": "#cccccc",
    "debugConsole.warningForeground": "#cca700",
    "debugConsoleInputIcon.foreground": "#cccccc",
    "debugIcon.breakpointCurrentStackframeForeground": "#ffcc00",
    "debugIcon.breakpointDisabledForeground": "#848484",
    "debugIcon.breakpointForeground": "#e51400",
    "debugIcon.breakpointStackframeForeground": "#89d185",
    "debugIcon.breakpointUnverifiedForeground": "#848484",
    "debugIcon.continueForeground": "#75beff",
    "debugIcon.disconnectForeground": "#f48771",
    "debugIcon.pauseForeground": "#75beff",
    "debugIcon.restartForeground": "#89d185",
    "debugIcon.startForeground": "#89d185",
    "debugIcon.stepBackForeground": "#75beff",
    "debugIcon.stepIntoForeground": "#75beff",
    "debugIcon.stepOutForeground": "#75beff",
    "debugIcon.stepOverForeground": "#75beff",
    "debugIcon.stopForeground": "#f48771",
    "debugTokenExpression.boolean": "#4e94ce",
    "debugTokenExpression.error": "#f48771",
    "debugTokenExpression.name": "#c586c0",
    "debugTokenExpression.number": "#b5cea8",
    "debugTokenExpression.string": "#ce9178",
    "debugTokenExpression.value": "#cccccc99",
    "debugView.exceptionLabelBackground": "#6c2022",
    "debugView.exceptionLabelForeground": "#cccccc",
    "debugView.stateLabelBackground": "#88888844",
    "debugView.stateLabelForeground": "#cccccc",
    "debugView.valueChangedHighlight": "#569cd6",
    descriptionForeground: "#ccccccb3",
    "diffEditor.diagonalFill": "#cccccc33",
    "diffEditor.insertedLineBackground": "#9bb95533",
    "diffEditor.removedLineBackground": "#ff000033",
    disabledForeground: "#cccccc80",
    "editor.focusedStackFrameHighlightBackground": "#7abd7a4d",
    "editor.inlineValuesBackground": "#ffc80033",
    "editor.inlineValuesForeground": "#ffffff80",
    "editor.linkedEditingBackground": "#ff00004d",
    "editor.snippetFinalTabstopHighlightBorder": "#525252",
    "editor.snippetTabstopHighlightBackground": "#7c7c7c4d",
    "editor.stackFrameHighlightBackground": "#ffff0033",
    "editor.symbolHighlightBackground": "#ea5c0055",
    "editorBracketPairGuide.activeBackground1": "#00000000",
    "editorBracketPairGuide.activeBackground2": "#00000000",
    "editorBracketPairGuide.activeBackground3": "#00000000",
    "editorBracketPairGuide.activeBackground4": "#00000000",
    "editorBracketPairGuide.activeBackground5": "#00000000",
    "editorBracketPairGuide.activeBackground6": "#00000000",
    "editorBracketPairGuide.background1": "#00000000",
    "editorBracketPairGuide.background2": "#00000000",
    "editorBracketPairGuide.background3": "#00000000",
    "editorBracketPairGuide.background4": "#00000000",
    "editorBracketPairGuide.background5": "#00000000",
    "editorBracketPairGuide.background6": "#00000000",
    "editorCommentsWidget.rangeActiveBackground": "#353f4f1a",
    "editorCommentsWidget.rangeActiveBorder": "#353f4f66",
    "editorCommentsWidget.rangeBackground": "#353f4f1a",
    "editorCommentsWidget.rangeBorder": "#353f4f66",
    "editorCommentsWidget.resolvedBorder": "#cccccc80",
    "editorCommentsWidget.unresolvedBorder": "#353f4f",
    "editorGhostText.foreground": "#ffffff56",
    "editorGroup.dropBackground": "#53595d80",
    "editorGroup.dropIntoPromptBackground": "#0f172a",
    "editorGroup.dropIntoPromptForeground": "#cccccc",
    "editorGroupHeader.noTabsBackground": "#1e293b",
    "editorHint.foreground": "#eeeeeeb3",
    "editorHoverWidget.highlightForeground": "#0097fb",
    "editorHoverWidget.statusBarBackground": "#243147",
    "editorInlayHint.background": "#15334f99",
    "editorInlayHint.foreground": "#38bdf8cc",
    "editorInlayHint.parameterBackground": "#15334f99",
    "editorInlayHint.parameterForeground": "#38bdf8cc",
    "editorInlayHint.typeBackground": "#15334f99",
    "editorInlayHint.typeForeground": "#38bdf8cc",
    "editorLightBulb.foreground": "#ffcc00",
    "editorLightBulbAutoFix.foreground": "#75beff",
    "editorMarkerNavigationError.headerBackground": "#f487710f",
    "editorMarkerNavigationInfo.headerBackground": "#75beff0f",
    "editorMarkerNavigationWarning.headerBackground": "#cca7000f",
    "editorOverviewRuler.addedForeground": "#587c0c99",
    "editorOverviewRuler.bracketMatchForeground": "#a0a0a0",
    "editorOverviewRuler.commonContentForeground": "#383838",
    "editorOverviewRuler.currentContentForeground": "#367366",
    "editorOverviewRuler.deletedForeground": "#94151b99",
    "editorOverviewRuler.errorForeground": "#ff1212b3",
    "editorOverviewRuler.findMatchForeground": "#d186167e",
    "editorOverviewRuler.incomingContentForeground": "#395f8f",
    "editorOverviewRuler.infoForeground": "#75beff",
    "editorOverviewRuler.modifiedForeground": "#0c7d9d99",
    "editorOverviewRuler.rangeHighlightForeground": "#007acc99",
    "editorOverviewRuler.selectionHighlightForeground": "#a0a0a0cc",
    "editorOverviewRuler.warningForeground": "#cca700",
    "editorOverviewRuler.wordHighlightForeground": "#a0a0a0cc",
    "editorOverviewRuler.wordHighlightStrongForeground": "#c0a0c0cc",
    "editorPane.background": "#1e293b",
    "editorStickyScroll.background": "#1e293b",
    "editorStickyScrollHover.background": "#2a2d2e",
    "editorSuggestWidget.focusHighlightForeground": "#0097fb",
    "editorSuggestWidgetStatus.foreground": "#efeff180",
    "editorUnicodeHighlight.background": "#bd9b0326",
    "editorUnicodeHighlight.border": "#bd9b03",
    "editorUnnecessaryCode.opacity": "#000000aa",
    "editorWidget.border": "#454545",
    errorForeground: "#f48771",
    "errorLens.errorBackground": "#e454541b",
    "errorLens.errorBackgroundLight": "#e4545420",
    "errorLens.errorForeground": "#ff6464",
    "errorLens.errorForegroundLight": "#e45454",
    "errorLens.errorMessageBackground": "#e4545419",
    "errorLens.hintBackground": "#17a2a220",
    "errorLens.hintBackgroundLight": "#17a2a220",
    "errorLens.hintForeground": "#2faf64",
    "errorLens.hintForegroundLight": "#2faf64",
    "errorLens.hintMessageBackground": "#17a2a219",
    "errorLens.infoBackground": "#00b7e420",
    "errorLens.infoBackgroundLight": "#00b7e420",
    "errorLens.infoForeground": "#00b7e4",
    "errorLens.infoForegroundLight": "#00b7e4",
    "errorLens.infoMessageBackground": "#00b7e419",
    "errorLens.statusBarErrorForeground": "#ff6464",
    "errorLens.statusBarHintForeground": "#2faf64",
    "errorLens.statusBarIconErrorForeground": "#ff6464",
    "errorLens.statusBarIconWarningForeground": "#fa973a",
    "errorLens.statusBarInfoForeground": "#00b7e4",
    "errorLens.statusBarWarningForeground": "#fa973a",
    "errorLens.warningBackground": "#ff942f1b",
    "errorLens.warningBackgroundLight": "#ff942f20",
    "errorLens.warningForeground": "#fa973a",
    "errorLens.warningForegroundLight": "#ff942f",
    "errorLens.warningMessageBackground": "#ff942f19",
    "extensionBadge.remoteBackground": "#15334f",
    "extensionBadge.remoteForeground": "#38bdf8",
    "extensionButton.prominentBackground": "#0ea5e9",
    "extensionButton.prominentForeground": "#ffffff",
    "extensionButton.prominentHoverBackground": "#38bdf8",
    "extensionIcon.preReleaseForeground": "#1d9271",
    "extensionIcon.sponsorForeground": "#d758b3",
    "extensionIcon.starForeground": "#ff8e00",
    "extensionIcon.verifiedForeground": "#3794ff",
    "gitDecoration.renamedResourceForeground": "#73c991",
    "gitlens.closedAutolinkedIssueIconColor": "#a371f7",
    "gitlens.closedPullRequestIconColor": "#f85149",
    "gitlens.decorations.addedForegroundColor": "#81b88b",
    "gitlens.decorations.branchAheadForegroundColor": "#35b15e",
    "gitlens.decorations.branchBehindForegroundColor": "#b15e35",
    "gitlens.decorations.branchDivergedForegroundColor": "#d8af1b",
    "gitlens.decorations.branchMissingUpstreamForegroundColor": "#c74e39",
    "gitlens.decorations.branchUnpublishedForegroundColor": "#35b15e",
    "gitlens.decorations.branchUpToDateForegroundColor": "#cccccc",
    "gitlens.decorations.copiedForegroundColor": "#73c991",
    "gitlens.decorations.deletedForegroundColor": "#c74e39",
    "gitlens.decorations.ignoredForegroundColor": "#8c8c8c",
    "gitlens.decorations.modifiedForegroundColor": "#e2c08d",
    "gitlens.decorations.renamedForegroundColor": "#73c991",
    "gitlens.decorations.untrackedForegroundColor": "#73c991",
    "gitlens.decorations.worktreeView.hasUncommittedChangesForegroundColor": "#e2c08d",
    "gitlens.graphLane10Color": "#2ece9d",
    "gitlens.graphLane1Color": "#15a0bf",
    "gitlens.graphLane2Color": "#0669f7",
    "gitlens.graphLane3Color": "#8e00c2",
    "gitlens.graphLane4Color": "#c517b6",
    "gitlens.graphLane5Color": "#d90171",
    "gitlens.graphLane6Color": "#cd0101",
    "gitlens.graphLane7Color": "#f25d2e",
    "gitlens.graphLane8Color": "#f2ca33",
    "gitlens.graphLane9Color": "#7bd938",
    "gitlens.gutterBackgroundColor": "#ffffff13",
    "gitlens.gutterForegroundColor": "#bebebe",
    "gitlens.gutterUncommittedForegroundColor": "#00bcf299",
    "gitlens.lineHighlightBackgroundColor": "#00bcf233",
    "gitlens.lineHighlightOverviewRulerColor": "#00bcf299",
    "gitlens.mergedPullRequestIconColor": "#a371f7",
    "gitlens.openAutolinkedIssueIconColor": "#3fb950",
    "gitlens.openPullRequestIconColor": "#3fb950",
    "gitlens.trailingLineBackgroundColor": "#00000000",
    "gitlens.trailingLineForegroundColor": "#99999959",
    "gitlens.unpublishedChangesIconColor": "#35b15e",
    "gitlens.unpublishedCommitIconColor": "#35b15e",
    "gitlens.unpulledChangesIconColor": "#b15e35",
    "inputOption.hoverBackground": "#5a5d5e80",
    "inputValidation.errorBackground": "#5a1d1d",
    "inputValidation.errorBorder": "#be1100",
    "inputValidation.infoBackground": "#063b49",
    "inputValidation.infoBorder": "#007acc",
    "inputValidation.warningBackground": "#352a05",
    "inputValidation.warningBorder": "#b89500",
    "interactive.activeCodeBorder": "#353f4f",
    "interactive.inactiveCodeBorder": "#1e293b",
    "keybindingLabel.background": "#8080802b",
    "keybindingLabel.border": "#33333399",
    "keybindingLabel.bottomBorder": "#44444499",
    "keybindingLabel.foreground": "#cccccc",
    "keybindingTable.headerBackground": "#cccccc0a",
    "keybindingTable.rowsBackground": "#cccccc0a",
    "list.deemphasizedForeground": "#8c8c8c",
    "list.errorForeground": "#f88070",
    "list.filterMatchBackground": "#ea5c0055",
    "list.filterMatchBorder": "#ffffff00",
    "list.focusHighlightForeground": "#0097fb",
    "list.focusOutline": "#007fd4",
    "list.invalidItemForeground": "#b89500",
    "list.warningForeground": "#cca700",
    "listFilterWidget.shadow": "#0000005c",
    "mergeEditor.change.background": "#9bb95533",
    "mergeEditor.change.word.background": "#9ccc2c33",
    "mergeEditor.conflict.handled.minimapOverViewRuler": "#adaca8ee",
    "mergeEditor.conflict.handledFocused.border": "#c1c1c1cc",
    "mergeEditor.conflict.handledUnfocused.border": "#86868649",
    "mergeEditor.conflict.unhandled.minimapOverViewRuler": "#fcba03",
    "mergeEditor.conflict.unhandledFocused.border": "#ffa600",
    "mergeEditor.conflict.unhandledUnfocused.border": "#ffa6007a",
    "mergeEditor.conflictingLines.background": "#ffea0047",
    "minimap.foregroundOpacity": "#000000",
    "minimap.selectionOccurrenceHighlight": "#676767",
    "minimapSlider.activeBackground": "#a1a1a180",
    "minimapSlider.background": "#67676780",
    "minimapSlider.hoverBackground": "#7b7b7b80",
    "notebook.cellBorderColor": "#1e293b",
    "notebook.cellEditorBackground": "#0f172a",
    "notebook.cellInsertionIndicator": "#007fd4",
    "notebook.cellStatusBarItemHoverBackground": "#ffffff26",
    "notebook.cellToolbarSeparator": "#80808059",
    "notebook.editorBackground": "#1e293b",
    "notebook.focusedCellBorder": "#007fd4",
    "notebook.focusedEditorBorder": "#007fd4",
    "notebook.inactiveFocusedCellBorder": "#1e293b",
    "notebook.selectedCellBackground": "#1e293b",
    "notebook.selectedCellBorder": "#1e293b",
    "notebook.symbolHighlightBackground": "#ffffff0b",
    "notebookScrollbarSlider.activeBackground": "#a1a1a1",
    "notebookScrollbarSlider.background": "#676767",
    "notebookScrollbarSlider.hoverBackground": "#7b7b7b",
    "notebookStatusErrorIcon.foreground": "#f48771",
    "notebookStatusRunningIcon.foreground": "#cccccc",
    "notebookStatusSuccessIcon.foreground": "#89d185",
    "notificationLink.foreground": "#3794ff",
    "panel.dropBorder": "#e7e7e7",
    "panelSection.dropBackground": "#53595d80",
    "panelSectionHeader.background": "#80808033",
    "ports.iconRunningProcessForeground": "#16825d",
    "problemsErrorIcon.foreground": "#f48771",
    "problemsInfoIcon.foreground": "#75beff",
    "problemsWarningIcon.foreground": "#cca700",
    "quickInput.background": "#0f172a",
    "quickInput.foreground": "#cccccc",
    "quickInputList.focusBackground": "#1e293b",
    "quickInputList.focusForeground": "#ffffff",
    "quickInputTitle.background": "#ffffff1b",
    "sash.hoverBorder": "#007fd4",
    "scm.providerBorder": "#454545",
    "searchEditor.findMatchBackground": "#ea5c0038",
    "searchEditor.findMatchBorder": "#ffffff00",
    "searchEditor.textInputBorder": "#00000000",
    "settings.checkboxBackground": "#2b3447",
    "settings.checkboxBorder": "#00000000",
    "settings.checkboxForeground": "#cccccc",
    "settings.dropdownBackground": "#0f172a",
    "settings.dropdownBorder": "#00000000",
    "settings.dropdownForeground": "#cccccc",
    "settings.dropdownListBorder": "#454545",
    "settings.focusedRowBorder": "#ffffff1f",
    "settings.headerBorder": "#1e293b",
    "settings.modifiedItemIndicator": "#0c7d9d",
    "settings.numberInputBackground": "#0f172a",
    "settings.numberInputBorder": "#00000000",
    "settings.numberInputForeground": "#cccccc",
    "settings.rowHoverBackground": "#1e293b4d",
    "settings.sashBorder": "#1e293b",
    "settings.textInputBackground": "#0f172a",
    "settings.textInputBorder": "#00000000",
    "settings.textInputForeground": "#cccccc",
    "sideBySideEditor.horizontalBorder": "#151515",
    "sideBySideEditor.verticalBorder": "#151515",
    "statusBar.focusBorder": "#ffffff",
    "statusBarItem.compactHoverBackground": "#ffffff33",
    "statusBarItem.errorBackground": "#c72e0f",
    "statusBarItem.errorForeground": "#ffffff",
    "statusBarItem.focusBorder": "#ffffff",
    "statusBarItem.prominentBackground": "#00000080",
    "statusBarItem.prominentForeground": "#ffffff",
    "statusBarItem.prominentHoverBackground": "#0000004d",
    "statusBarItem.warningBackground": "#7a6400",
    "statusBarItem.warningForeground": "#ffffff",
    "symbolIcon.arrayForeground": "#cccccc",
    "symbolIcon.booleanForeground": "#cccccc",
    "symbolIcon.classForeground": "#ee9d28",
    "symbolIcon.colorForeground": "#cccccc",
    "symbolIcon.constantForeground": "#cccccc",
    "symbolIcon.constructorForeground": "#b180d7",
    "symbolIcon.enumeratorForeground": "#ee9d28",
    "symbolIcon.enumeratorMemberForeground": "#75beff",
    "symbolIcon.eventForeground": "#ee9d28",
    "symbolIcon.fieldForeground": "#75beff",
    "symbolIcon.fileForeground": "#cccccc",
    "symbolIcon.folderForeground": "#cccccc",
    "symbolIcon.functionForeground": "#b180d7",
    "symbolIcon.interfaceForeground": "#75beff",
    "symbolIcon.keyForeground": "#cccccc",
    "symbolIcon.keywordForeground": "#cccccc",
    "symbolIcon.methodForeground": "#b180d7",
    "symbolIcon.moduleForeground": "#cccccc",
    "symbolIcon.namespaceForeground": "#cccccc",
    "symbolIcon.nullForeground": "#cccccc",
    "symbolIcon.numberForeground": "#cccccc",
    "symbolIcon.objectForeground": "#cccccc",
    "symbolIcon.operatorForeground": "#cccccc",
    "symbolIcon.packageForeground": "#cccccc",
    "symbolIcon.propertyForeground": "#cccccc",
    "symbolIcon.referenceForeground": "#cccccc",
    "symbolIcon.snippetForeground": "#cccccc",
    "symbolIcon.stringForeground": "#cccccc",
    "symbolIcon.structForeground": "#cccccc",
    "symbolIcon.textForeground": "#cccccc",
    "symbolIcon.typeParameterForeground": "#cccccc",
    "symbolIcon.unitForeground": "#cccccc",
    "symbolIcon.variableForeground": "#75beff",
    "tab.activeModifiedBorder": "#3399cc",
    "tab.inactiveModifiedBorder": "#3399cc80",
    "tab.lastPinnedBorder": "#585858",
    "tab.unfocusedActiveBackground": "#1e293b",
    "tab.unfocusedActiveBorder": "#00000000",
    "tab.unfocusedActiveBorderTop": "#00000000",
    "tab.unfocusedActiveForeground": "#7dd3fc80",
    "tab.unfocusedActiveModifiedBorder": "#3399cc80",
    "tab.unfocusedHoverBackground": "#1e293b48",
    "tab.unfocusedHoverBorder": "#1e293b80",
    "tab.unfocusedInactiveBackground": "#283447",
    "tab.unfocusedInactiveForeground": "#ffffff40",
    "tab.unfocusedInactiveModifiedBorder": "#3399cc40",
    "terminal.dropBackground": "#53595d80",
    "terminal.findMatchBackground": "#515c6a",
    "terminal.findMatchHighlightBackground": "#ea5c0055",
    "terminal.inactiveSelectionBackground": "#ffffff08",
    "terminal.tab.activeBorder": "#00000000",
    "terminalCommandDecoration.defaultBackground": "#ffffff40",
    "terminalCommandDecoration.errorBackground": "#f14c4c",
    "terminalCommandDecoration.successBackground": "#1b81a8",
    "terminalOverviewRuler.cursorForeground": "#a0a0a0cc",
    "terminalOverviewRuler.findMatchForeground": "#d186167e",
    "testing.iconErrored": "#f14c4c",
    "testing.iconFailed": "#f14c4c",
    "testing.iconPassed": "#73c991",
    "testing.iconQueued": "#cca700",
    "testing.iconSkipped": "#848484",
    "testing.iconUnset": "#848484",
    "testing.message.error.decorationForeground": "#f48771",
    "testing.message.error.lineBackground": "#ff000033",
    "testing.message.info.decorationForeground": "#64748b80",
    "testing.peekBorder": "#f48771",
    "testing.peekHeaderBackground": "#f487711a",
    "testing.runAction": "#73c991",
    "textBlockQuote.background": "#7f7f7f1a",
    "textBlockQuote.border": "#007acc80",
    "textCodeBlock.background": "#0a0a0a66",
    "textLink.activeForeground": "#3794ff",
    "textPreformat.foreground": "#d7ba7d",
    "textSeparator.foreground": "#ffffff2e",
    "toolbar.activeBackground": "#63666750",
    "toolbar.hoverBackground": "#5a5d5e50",
    "tree.tableColumnsBorder": "#cccccc20",
    "tree.tableOddRowsBackground": "#cccccc0a",
    "welcomePage.progress.background": "#0f172a",
    "welcomePage.progress.foreground": "#3794ff",
    "welcomePage.tileBackground": "#0f172a",
    "welcomePage.tileHoverBackground": "#121c32",
    "welcomePage.tileShadow": "#0000005c",
    "activityBar.activeFocusBorder": null,
    "button.border": null,
    "commandCenter.background": null,
    contrastActiveBorder: null,
    contrastBorder: null,
    "diffEditor.insertedTextBorder": null,
    "diffEditor.removedTextBorder": null,
    "diffEditorGutter.insertedLineBackground": null,
    "diffEditorGutter.removedLineBackground": null,
    "diffEditorOverview.insertedForeground": null,
    "diffEditorOverview.removedForeground": null,
    "dropdown.listBackground": null,
    "editor.selectionForeground": null,
    "editor.snippetFinalTabstopHighlightBackground": null,
    "editor.snippetTabstopHighlightBorder": null,
    "editor.symbolHighlightBorder": null,
    "editor.wordHighlightBorder": null,
    "editor.wordHighlightStrongBorder": null,
    "editorGhostText.background": null,
    "editorGhostText.border": null,
    "editorGroup.dropIntoPromptBorder": null,
    "editorGroup.focusedEmptyBorder": null,
    "editorGroupHeader.tabsBorder": null,
    "editorHint.border": null,
    "editorSuggestWidget.selectedIconForeground": null,
    "editorUnnecessaryCode.border": null,
    "inputValidation.errorForeground": null,
    "inputValidation.infoForeground": null,
    "inputValidation.warningForeground": null,
    "list.activeSelectionIconForeground": null,
    "list.focusAndSelectionOutline": null,
    "list.inactiveFocusBackground": null,
    "list.inactiveFocusOutline": null,
    "list.inactiveSelectionIconForeground": null,
    "menubar.selectionBorder": null,
    "merge.border": null,
    "notebook.cellHoverBackground": null,
    "notebook.focusedCellBackground": null,
    "notebook.inactiveSelectedCellBorder": null,
    "notebook.outputContainerBackgroundColor": null,
    "notebook.outputContainerBorderColor": null,
    "panelInput.border": null,
    "panelSectionHeader.border": null,
    "panelSectionHeader.foreground": null,
    "quickInput.list.focusBackground": null,
    "quickInputList.focusIconForeground": null,
    "statusBar.border": null,
    "statusBar.debuggingBorder": null,
    "statusBar.noFolderBorder": null,
    "statusBarItem.settingsProfilesBackground": null,
    "statusBarItem.settingsProfilesForeground": null,
    "tab.hoverForeground": null,
    "tab.unfocusedHoverForeground": null,
    "terminal.background": null,
    "terminal.findMatchBorder": null,
    "terminal.findMatchHighlightBorder": null,
    "terminal.selectionForeground": null,
    "testing.message.info.lineBackground": null,
    "toolbar.hoverOutline": null,
    "welcomePage.background": null,
    "window.activeBorder": null,
    "window.inactiveBorder": null,
  },
  tokenColors: [
    {
      scope: "entity.name.tag",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "comment",
      settings: {
        foreground: "#5C6773",
        fontStyle: "italic",
      },
    },
    {
      scope: "keyword",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "keyword.control, keyword.operator.new",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "keyword.operator",
      settings: {
        foreground: "#E6E6E6",
      },
    },
    {
      scope: "keyword.operator.logical, keyword.operator.comparison",
      settings: {
        foreground: "#FF9473",
      },
    },
    {
      scope: "storage",
      settings: {
        foreground: "#FF9473",
        fontStyle: "italic",
      },
    },
    {
      scope: "constant",
      settings: {
        foreground: "#D6D6D6",
        fontStyle: "italic",
      },
    },
    {
      scope: "constant.character.escape",
      settings: {
        foreground: "#8CA6BD",
      },
    },
    {
      scope: "variable",
      settings: {
        foreground: "#E6E6E6",
      },
    },
    {
      scope: "variable.parameter",
      settings: {
        foreground: "#BBBBBB",
      },
    },
    {
      scope: "meta.object-binding-pattern-variable.js variable",
      settings: {
        foreground: "#FF9473",
      },
    },
    {
      scope: "variable.other.constant, variable.language.this, variable.interpolation",
      settings: {
        foreground: "#FFA7D3",
      },
    },
    {
      scope: "variable.language.this",
      settings: {
        fontStyle: "italic",
      },
    },
    {
      scope: "variable.other.object",
      settings: {
        foreground: "#FFA7D3",
      },
    },
    {
      scope: "variable.other.property",
      settings: {
        foreground: "#D6D6D6",
      },
    },
    {
      scope: "invalid.illegal",
      settings: {
        foreground: "#FF4551",
      },
    },
    {
      scope: "invalid.deprecated",
      settings: {
        foreground: "#FF4551CC",
      },
    },
    {
      scope: "string",
      settings: {
        foreground: "#7DD3FC",
      },
    },
    {
      scope: "punctuation.definition.template-expression",
      settings: {
        foreground: "#FF9473",
      },
    },
    {
      scope: "support",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "support.class",
      settings: {
        foreground: "#FF9473",
      },
    },
    {
      scope: "support.type.object.module.js",
      settings: {
        foreground: "#C38EFD",
      },
    },
    {
      scope: "support.function",
      settings: {
        foreground: "#97E5F1",
      },
    },
    {
      scope: "entity.name.function",
      settings: {
        foreground: "#97E5F1",
        fontStyle: "italic",
      },
    },
    {
      scope: "entity.other.inherited-class",
      settings: {
        foreground: "#FFA7D3",
      },
    },
    {
      scope: "entity.name.tag.yaml",
      settings: {
        foreground: "#FF9473",
      },
    },
    {
      scope: "meta.decorator punctuation.decorator",
      settings: {
        foreground: "#FF9473",
      },
    },
    {
      scope: "meta.decorator variable",
      settings: {
        foreground: "#97E5F1",
      },
    },
    {
      scope: "keyword.other.special-method",
      settings: {
        foreground: "#8CA6BD",
      },
    },
    {
      scope: "keyword.control.at-rule",
      settings: {
        foreground: "#C38EFD",
      },
    },
    {
      scope: "keyword.other.important",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "variable.interpolation",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "meta.source.handlebars entity.name.tag",
      settings: {
        foreground: "#97E5F1",
      },
    },
    {
      scope:
        "punctuation.definition.expression, punctuation.definition.subexpression, punctuation.definition.block.unescaped, punctuation.definition.tag",
      settings: {
        foreground: "#F472B687",
      },
    },
    {
      scope: "entity.name.function.expression",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "entity.unescaped.expression",
      settings: {
        foreground: "#C38EFD",
      },
    },
    {
      scope: "constant.other.symbol",
      settings: {
        foreground: "#7EF2AE",
      },
    },
    {
      scope: "entity.expression variable.parameter.name",
      settings: {
        foreground: "#C3A8FE",
      },
    },
    {
      scope: "entity.expression variable.parameter.value",
      settings: {
        foreground: "#97E5F1",
      },
    },
    {
      scope: "entity.expression support.function.builtin",
      settings: {
        foreground: "#FFA7D3",
      },
    },
    {
      scope: "entity.name.tag.html",
      settings: {
        foreground: "#FF9473",
      },
    },
    {
      scope: "entity.other.attribute-name.handlebars",
      settings: {
        foreground: "#FF9473",
      },
    },
    {
      scope: "support.class.component",
      settings: {
        foreground: "#FF9473",
        fontStyle: "italic",
      },
    },
    {
      scope: "meta.tag.js entity.name.tag",
      settings: {
        foreground: "#FF9473",
      },
    },
    {
      scope: "entity.other.attribute-name",
      settings: {
        foreground: "#D6D6D6",
        fontStyle: "italic",
      },
    },
    {
      scope: "markup.bold",
      settings: {
        foreground: "#FF9473",
        fontStyle: "bold",
      },
    },
    {
      scope: "punctuation.definition.bold.markdown",
      settings: {
        foreground: "#FF9473",
        fontStyle: "bold",
      },
    },
    {
      scope: "markup.changed",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "markup.deleted",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "markup.italic",
      settings: {
        foreground: "#FFA7D3",
        fontStyle: "italic",
      },
    },
    {
      scope: "punctuation.definition.italic.markdown",
      settings: {
        foreground: "#F472B6",
        fontStyle: "italic",
      },
    },
    {
      scope: "markup.inserted",
      settings: {
        foreground: "#7EF2AE",
      },
    },
    {
      scope: "punctuation.definition.heading",
      settings: {
        foreground: "#7EF2AE",
      },
    },
    {
      scope: "entity.name.section.markdown",
      settings: {
        foreground: "#BBBBBB",
      },
    },
    {
      scope: "markup.quote",
      settings: {
        foreground: "#C3A8FE",
      },
    },
    {
      scope: "markup.inline.raw",
      settings: {
        foreground: "#7EF2AE",
        fontStyle: "italic",
      },
    },
    {
      scope: "beginning.punctuation.definition.list",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "markup.fenced_code.block.markdown punctuation.definition.markdown",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "fenced_code.block.language",
      settings: {
        foreground: "#BBBBBB",
        fontStyle: "italic",
      },
    },
    {
      scope: "string.other.link",
      settings: {
        foreground: "#BBBBBB",
        fontStyle: "",
      },
    },
    {
      scope: "meta.link.inline.markdown",
      settings: {
        foreground: "#8CA6BD",
        fontStyle: "italic",
      },
    },
    {
      scope: "text.html.markdown punctuation.definition.string",
      settings: {
        foreground: "#FF9473",
        fontStyle: "",
      },
    },
    {
      scope: "entity.name.type.class.js",
      settings: {
        foreground: "#97E5F1",
      },
    },
    {
      scope: "keyword.control.as.js",
      settings: {
        foreground: "#FFA7D3",
      },
    },
    {
      scope: "keyword.control.from.js.jsx",
      settings: {
        foreground: "#FFA7D3",
      },
    },
    {
      scope: "keyword.control.export.js",
      settings: {
        foreground: "#C38EFD",
      },
    },
    {
      scope: "entity.name.tag.js.jsx, support.class.component.js.jsx",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "variable.language.super.js.jsx",
      settings: {
        foreground: "#8CA6BD",
      },
    },
    {
      scope:
        "meta.tag.structure.any.html, meta.tag.other.html, entity.name.tag.html, meta.tag.metadata.script.html, entity.name.tag.jade",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope:
        "entity.name.tag.inline.any.html, entity.name.tag.other.html, entity.name.tag.block.any.html",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "entity.name.tag.css",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "support.type.property-name.css",
      settings: {
        foreground: "#7DD3FC",
      },
    },
    {
      scope: "variable.scss",
      settings: {
        foreground: "#FFA7D3",
      },
    },
    {
      scope: "entity.name.tag.reference.scss",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope:
        "keyword.other.unit.rem.css, keyword.other.unit.vh.css, keyword.other.unit.px.css, keyword.other.unit.em.css, keyword.other.unit.deg.css, keyword.other.unit.percentage.css",
      settings: {
        foreground: "#99F6E4",
      },
    },
    {
      scope: "string.regexp",
      settings: {
        foreground: "#97E5F1",
      },
    },
    {
      scope: "string.regexp keyword, string.regexp keyword.control",
      settings: {
        foreground: "#F472B6",
        fontStyle: "",
      },
    },
    {
      scope: "string.regexp keyword.operator",
      settings: {
        foreground: "#FFA7D3",
      },
    },
    {
      scope: "comment.block.documentation",
      settings: {
        fontStyle: "",
      },
    },
    {
      scope: "entity.name.type.instance.jsdoc punctuation.definition",
      settings: {
        foreground: "#F472B6",
        fontStyle: "italic",
      },
    },
    {
      scope: "entity.name.type.instance.jsdoc",
      settings: {
        foreground: "#CDCDCD",
        fontStyle: "italic",
      },
    },
    {
      scope: "comment.block storage",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope:
        "comment.block storage.custom, variable.other.jsdoc, variable.other.jsdoc punctuation.definition.string",
      settings: {
        foreground: "#FFA7D3",
      },
    },
    {
      scope: "meta.tag.xml",
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "meta.function-call.python",
      settings: {
        foreground: "#A9C3D9",
        fontStyle: "italic",
      },
    },
    {
      scope: "support.type.property-name.json",
      settings: {
        foreground: "#CFAFFA",
      },
    },
    {
      scope: ["entity.name.type"],
      settings: {
        foreground: "#97E5F1",
        fontStyle: "",
      },
    },
    {
      scope: [
        "entity.name.type.type-parameter",
        "meta.indexer.mappedtype.declaration entity.name.type",
        "meta.type.parameters entity.name.type",
      ],
      settings: {
        foreground: "#F472B6",
      },
    },
    {
      scope: "token.info-token",
      settings: {
        foreground: "#6796E6",
      },
    },
    {
      scope: "token.warn-token",
      settings: {
        foreground: "#CD9731",
      },
    },
    {
      scope: "token.error-token",
      settings: {
        foreground: "#F44747",
      },
    },
    {
      scope: "token.debug-token",
      settings: {
        foreground: "#B267E6",
      },
    },
    {
      scope: ["entity.name.type"],
      settings: {
        foreground: "#97E5F1",
        fontStyle: "",
      },
    },
    {
      scope: [
        "entity.name.type.type-parameter",
        "meta.indexer.mappedtype.declaration entity.name.type",
        "meta.type.parameters entity.name.type",
      ],
      settings: {
        foreground: "#FF9473",
      },
    },
  ],
};
